In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
loan_data = pd.read_csv("C:/Users/user/Desktop/New folder (2)/Loan.csv")
loan_data.head()

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179140,0.070210,1,36.0

In [ ]:
loan_data.columns

Index(['ApplicationDate', 'Age', 'AnnualIncome', 'CreditScore',
       'EmploymentStatus', 'EducationLevel', 'Experience', 'LoanAmount',
       'LoanDuration', 'MaritalStatus', 'NumberOfDependents',
       'HomeOwnershipStatus', 'MonthlyDebtPayments',
       'CreditCardUtilizationRate', 'NumberOfOpenCreditLines',
       'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory',
       'LoanPurpose', 'PreviousLoanDefaults', 'PaymentHistory',
       'LengthOfCreditHistory', 'SavingsAccountBalance',
       'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio', 'LoanApproved', 'RiskScore'],
      dtype='str')

In [ ]:
n = [ 'Age', 'AnnualIncome', 'CreditScore', 'Experience', 'LoanAmount',
       'LoanDuration', 'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio', 'LoanApproved', 'RiskScore']

In [ ]:
filtered_data = loan_data[n]

In [ ]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\user\anaconda3\envs\masterpierce\Lib\site-packages (from scikit-learn) (2.4.4)
INFO: pip is looking at multiple versions of scikit-learn to determine which version is compatible with other requirements. This could take a while.
  Downloading scikit_learn-1.7.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.7.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
  Downloading scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Downloading scikit_learn-1.6.0-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Downloading scikit_learn-1.6.0-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Downloading scikit_learn-1.6.0-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
  Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
INFO: pip is still looking at multiple versions of scikit-learn to determine which version is compatible with other requirements. This could take a while.
  Downloading scikit_learn-1.5.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.4.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.4.1.post1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting numpy<2.0,>=1.19.5 (from scikit-learn)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit_learn-1.3.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading scikit_learn-1.3.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Downloading scikit-learn-1.3.0.tar.gz (7.5 MB)
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     - -------------------------------------- 0.3/7.5 MB ? eta -:--:--
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     -- ------------------------------------- 0.5/7.5 MB 18.6 kB/s eta 0:06:15
     ---- ----------------------------------- 0.8/7.5 MB 14.8 kB/s eta 0:07:34
     ---- ----------------------------------- 0.8/7.5 MB 14.8 kB/s eta 0:07:34
     ---- ----------------------------------- 0.8/7.5 MB 14.8 kB/s eta 0:07:34

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Connection timed out while downloading.
  WARNING: Attempting to resume incomplete download (0 bytes/11 kB, attempt 1)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B7FB1370>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Connection timed out while downloading.
  WARNING: Attempting to resume incomplete download (0 bytes/11 kB, attempt 2)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/fa/c61a787e35f05f17fc10523f567677ec4eeee5f95aa4798dbbbcd9625617/scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata
  WARNING: Connection timed out while downloading.
  WARNING: Attempting to resume incomplete download (0 bytes/15 kB, attempt 1)
  WARNING: Connection timed out while downloading.
  WARNING: Attempting to resume incomplete download (0 bytes/15 kB, attempt 2)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/21/1d/3df58df8bd425f425df9f90b316618ace62b7f1f838ac1580191025cc735/scikit_learn-1.6.0-cp312-cp312-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B82A2C30>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/21/1d/3df58df8bd425f425df9f90b316618ace62b7f1f838ac1580191025cc735/scikit_learn-1.6.0-cp312-cp312-win_amd64.whl.metadata
  WARNING: Connection timed out while downloading.
  WARNING: Attempting to resume incomplete download (6.8 MB/7.5 MB, attempt 1)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B82A2ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B9894110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B7EC08C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A4A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6360>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Attempting to resume incomplete download (6.8 MB/7.5 MB, attempt 2)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A53D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B82A2B40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B9E87380>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98956D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B988F8F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Attempting to resume incomplete download (6.8 MB/7.5 MB, attempt 3)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6600>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A63F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6BA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Attempting to resume incomplete download (6.8 MB/7.5 MB, attempt 4)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A6F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A7320>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A7560>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A7770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A78F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Attempting to resume incomplete download (6.8 MB/7.5 MB, attempt 5)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A7C20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98A7EC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98D01D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B98D03E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000245B7DFE690>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/72/cd/4761675df1b3dd93072c89697278f3ed3dc004a60c034cd2603c43ff64b5/scikit-learn-1.3.0.tar.gz
  error: subprocess-exited-with-error

  × installing build dependencies for scikit-learn did not run successfully.
  │ exit code: 1
  ╰─> [3366 lines of output]
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
      Collecting setuptools
        Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
      Collecting wheel
        Downloading wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
      Collecting Cython>=0.29.33
        Downloading cython-3.2.4-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
      Collecting oldest-supported-numpy
        Downloading oldest_supported_numpy-2023.12.21-py3-none-any.whl.metadata (9.8 kB)
      Collecting scipy>=1.5.0
        Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
      Collecting packaging>=24.0 (from wheel)
        Downloading packaging-26.1-py3-none-any.whl.metadata (3.5 kB)
      Collecting numpy==1.26.2 (from oldest-supported-numpy)
        Downloading numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
      INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
      Collecting scipy>=1.5.0
        Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
        Downloading scipy-1.16.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
      Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
      Downloading wheel-0.46.3-py3-none-any.whl (30 kB)
      Downloading cython-3.2.4-cp312-cp312-win_amd64.whl (2.8 MB)
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
         ---------------------------------------- 0.0/2.8 MB ? eta -:--:--

     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     -------------- ------------------------- 2.6/7.5 MB 20.2 kB/s eta 0:04:01
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     --------------- ------------------------ 2.9/7.5 MB 15.8 kB/s eta 0:04:52
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ---------------- ----------------------- 3.1/7.5 MB 19.5 kB/s eta 0:03:43
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------ --------------------- 3.4/7.5 MB 19.6 kB/s eta 0:03:29
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33
     ------------------- -------------------- 3.7/7.5 MB 18.0 kB/s eta 0:03:33

         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 7.9/15.5 MB 21.1 kB/s eta 0:06:03
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         -------------------- ------------------- 8.1/15.5 MB 21.1 kB/s eta 0:05:49
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         --------------------- ------------------ 8.4/15.5 MB 19.7 kB/s eta 0:06:02
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.7/15.5 MB 20.8 kB/s eta 0:05:30
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03
         ---------------------- ----------------- 8.9/15.5 MB 21.8 kB/s eta 0:05:03

In [ ]:
import sklearn
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'sklearn'

In [2]:
laptop_data  = pd.read_csv('Laptop_price.csv')
laptop_data.head()

,Brand,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
0,Asus,3.830296,16,512,11.185147,2.641094,17395.093065
1,Acer,2.912833,4,1000,11.311372,3.260012,31607.605919
2,Lenovo,3.241627,4,256,11.853023,2.029061,9291.023542
3,Acer,3.806248,16,512,12.280360,4.573865,17436.728334
4,Acer,3.268097,32,1000,14.990877,4.193472,32917.990718

In [3]:
laptop_data.shape

(1000, 7)

In [4]:
laptop_data['Brand'].unique()

array(['Asus', 'Acer', 'Lenovo', 'HP', 'Dell'], dtype=object)

In [5]:
print(laptop_data.columns.tolist())

['Brand', 'Processor_Speed', 'RAM_Size', 'Storage_Capacity', 'Screen_Size', 'Weight', 'Price']

In [7]:
laptop_data.isna().sum().sum()

0

In [9]:
laptop_data.duplicated().sum()

0

In [10]:
laptop_data.describe()

,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2.750611,15.500000,584.576000,14.056790,3.466919,19604.187963
std,0.731796,10.988665,313.438517,1.705882,0.866541,9406.064880
min,1.511580,4.000000,256.000000,11.012111,2.000560,8570.012950
25%,2.089246,8.000000,256.000000,12.635523,2.717211,10114.012948
50%,2.760885,16.000000,512.000000,14.099643,3.464630,17287.241878
75%,3.362610,32.000000,1000.000000,15.528590,4.212583,31566.214754
max,3.998534,32.000000,1000.000000,16.985737,4.990728,33503.935037

In [13]:
numeric_data = laptop_data.select_dtypes(include = ['number'])
numeric_data.corr(method = 'pearson')

,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
Processor_Speed,1.000000,0.021391,-0.067576,-0.013425,-0.054603,-0.050737
RAM_Size,0.021391,1.000000,0.002111,-0.036002,-0.025382,0.061237
Storage_Capacity,-0.067576,0.002111,1.000000,-0.027560,0.041335,0.997908
Screen_Size,-0.013425,-0.036002,-0.027560,1.000000,0.021995,-0.026740
Weight,-0.054603,-0.025382,0.041335,0.021995,1.000000,0.038417
Price,-0.050737,0.061237,0.997908,-0.026740,0.038417,1.000000

In [15]:
laptop_data.groupby('Brand')['Price'].mean().sort_values(ascending  = False)

Brand
Acer      19984.613620
Lenovo    19974.929725
Asus      19854.238277
HP        19369.762930
Dell      18866.009978
Name: Price, dtype: float64

$$ \huge\textbf{Model Development}$$

In [16]:
laptop_data.columns

Index(['Brand', 'Processor_Speed', 'RAM_Size', 'Storage_Capacity',
       'Screen_Size', 'Weight', 'Price'],
      dtype='object')

In [17]:
y = laptop_data['Price']
X = laptop_data[['Processor_Speed', 'RAM_Size', 'Storage_Capacity']]

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train , X_test, y_train  , y_test = train_test_split(X , y , test_size = .2)

In [20]:
print(len(X_train))
print(len(y_train))

800
800

In [21]:
from sklearn.ensemble import RandomForestRegressor

rfrmodel = RandomForestRegressor()

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
param_gridrfr = {'max_depth':[2,5,10,15,20,25] , 
                 'max_features': ['auto' , 'log2'] , 
                 'n_estimators': [2,4,6,8,10,12]}

gridrfr = GridSearchCV(rfrmodel , param_gridrfr)

In [24]:
gridrfr.fit(X_train , y_train)

GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'max_depth': [2, 5, 10, 15, 20, 25],
                         'max_features': ['auto', 'log2'],
                         'n_estimators': [2, 4, 6, 8, 10, 12]})

In [25]:
gridrfr.best_params_

{'max_depth': 5, 'max_features': 'auto', 'n_estimators': 8}

In [27]:
prediction = gridrfr.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error

In [29]:
mean_absolute_error(y_test , prediction )

158.06839814391736

In [30]:
X.columns

Index(['Processor_Speed', 'RAM_Size', 'Storage_Capacity'], dtype='object')

In [31]:
gridrfr

GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'max_depth': [2, 5, 10, 15, 20, 25],
                         'max_features': ['auto', 'log2'],
                         'n_estimators': [2, 4, 6, 8, 10, 12]})

In [32]:
import joblib

In [33]:
joblib.dump(gridrfr , 'rf_model.pkl')

['rf_model.pkl']